---
##create user
user_name: test1
user_password: Test1!
user_group: test1

##change hostname
host_name: test-web01

##Apache
serveradmin: test@example.com
domain_name: test.onya-lab.site

##MySQL
root_password: Testtest991!

##dokcer-compose URL
docker_compose_url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64

##php version
php_version: 80

##php modules
php_modules:
  - "php"
  - "php-cli"
  - "php-devel"
  - "php-common"
  - "php-json"
  - "php-xml"
  - "php-mbstring"
  - "php-pdo"
  - "php-gd"
  - "php-process"
  - "php-intl"
  - "php-fpm"
  - "php-zip"
  - "php-bcmath"

##zabbix repository URL
zabbix_repository_url: https://repo.zabbix.com/zabbix/5.0/rhel/9/x86_64/zabbix-release-5.0-3.el9.noarch.rpm

##zabbix server IP
zabbix_server_ip: 192.168.33.80

##zabbix mysql pass
zabbix_dbpass: Zabbixmysql991!